version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Keep pip dependencies up to date
  - package-ecosystem: "pip"
    directory: "/"  # Set to the folder containing requirements.txt
    schedule:
      interval: "weekly"
