AWSTemplateFormatVersion: '2010-09-09'
Description: User API - 3 Lambda functions with API Gateway and DynamoDB

Parameters:
  Environment:
    Type: String
    Default: dev

Resources:

  #### DynamoDB Table ####
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "Users-${Environment}"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  #### IAM Role ####
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "UserApiLambdaRole-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: ["dynamodb:*"]
                Resource: "*"

  #### Lambda Functions ####
  CreateUserFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "CreateUser-${Environment}"
      Runtime: python3.11
      Handler: create_user.lambda_handler
      Code:
        S3Bucket: your-s3-bucket
        S3Key: lambda/create_user.zip
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable

  GetUserFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "GetUser-${Environment}"
      Runtime: python3.11
      Handler: get_user.lambda_handler
      Code:
        S3Bucket: your-s3-bucket
        S3Key: lambda/get_user.zip
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable

  DeleteUserFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "DeleteUser-${Environment}"
      Runtime: python3.11
      Handler: delete_user.lambda_handler
      Code:
        S3Bucket: your-s3-bucket
        S3Key: lambda/delete_user.zip
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable

  #### API Gateway ####
  Api:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "UserApi-${Environment}"

  UserResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref Api
      ParentId: !GetAtt Api.RootResourceId
      PathPart: user

  UserIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref Api
      ParentId: !Ref UserResource
      PathPart: "{id}"

  ## POST /user
  PostUserMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref Api
      ResourceId: !Ref UserResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateUserFunction.Arn}/invocations"

  ## GET /user/{id}
  GetUserMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref Api
      ResourceId: !Ref UserIdResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetUserFunction.Arn}/invocations"

  ## DELETE /user/{id}
  DeleteUserMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref Api
      ResourceId: !Ref UserIdResource
      HttpMethod: DELETE
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteUserFunction.Arn}/invocations"

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - PostUserMethod
      - GetUserMethod
      - DeleteUserMethod
    Properties:
      RestApiId: !Ref Api
      StageName: !Ref Environment

  #### Lambda Permissions ####
  AllowInvokeCreate:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CreateUserFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*/POST/user"

  AllowInvokeGet:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetUserFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*/GET/user/*"

  AllowInvokeDelete:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DeleteUserFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*/DELETE/user/*"

Outputs:
  ApiUrl:
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/user"
    Description: "Base URL for the User API"
